const OLD_LOGS_LIMIT = 1000;
const DISPLAYED_LOGS_LIMIT = 100;
const IS_OLD_LOGS_REQUIRED = true;

const TRACE_LOG_TYPE = 'TRACE';
const DEBUG_LOG_TYPE = 'DEBUG';
const WARN_LOG_TYPE = 'WARN';
const INFO_LOG_TYPE = 'INFO';
const ERROR_LOG_TYPE = 'ERROR';

export {
  OLD_LOGS_LIMIT,
  IS_OLD_LOGS_REQUIRED,
  DISPLAYED_LOGS_LIMIT,
  TRACE_LOG_TYPE,
  DEBUG_LOG_TYPE,
  WARN_LOG_TYPE,
  INFO_LOG_TYPE,
  ERROR_LOG_TYPE
};